export const FETCH_TASK_DATA = "FETCH_TASK_DATA";
export const SAVE_TASK_DATA = "SAVE_TASK_DATA";
export const CURRENT_FORM_DATA = "CURRENT_FORM_DATA";
export const CHIEF_FORM = "CHIEF_FORM";
export const PATIENT_OTHER_FORM = "PATIENT_OTHER_FORM";
export const MEDICATION_FORM = "MEDICATION_FORM";